.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-template-edit 1  "scriptisto-template-edit " 
.SH NAME
scriptisto\-template\-edit \- Opens an editor to modify an existing template, nice for quick edits
.SH SYNOPSIS
\fBscriptisto template edit\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITEMPLATE_NAME\fR> 
.SH DESCRIPTION
Opens an editor to modify an existing template, nice for quick edits
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fITEMPLATE_NAME\fR>
A name of the template to edit
