.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-template-rm 1  "scriptisto-template-rm " 
.SH NAME
scriptisto\-template\-rm \- Remove a custom template or reset it to the built\-in contents
.SH SYNOPSIS
\fBscriptisto\-template\-rm\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITEMPLATE_NAME\fR> 
.SH DESCRIPTION
Remove a custom template or reset it to the built\-in contents
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fITEMPLATE_NAME\fR>
A name of the template to remove
