.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-template-import 1  "scriptisto-template-import " 
.SH NAME
scriptisto\-template\-import \- Imports a template from file
.SH SYNOPSIS
\fBscriptisto\-template\-import\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Imports a template from file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIFILE\fR>
A filename of the script file. Extension will be stripped for the template name.
