.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-cache-info 1  "scriptisto-cache-info " 
.SH NAME
scriptisto\-cache\-info \- Shows information about the cache directory for the script
.SH SYNOPSIS
\fBscriptisto cache info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Shows information about the cache directory for the script
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIFILE\fR>
A filename of the script file.
