.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-cache-get 1  "scriptisto-cache-get " 
.SH NAME
scriptisto\-cache\-get \- Shows a particular item from "info" by name
.SH SYNOPSIS
\fBscriptisto\-cache\-get\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> <\fIFILE\fR> 
.SH DESCRIPTION
Shows a particular item from "info" by name
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fINAME\fR>
An item name, e.g. cache_path.
.TP
<\fIFILE\fR>
A filename of the script file.
