.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scriptisto-template-ls 1  "scriptisto-template-ls " 
.SH NAME
scriptisto\-template\-ls \- List all templates
.SH SYNOPSIS
\fBscriptisto template ls\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all templates
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
